name: taller_001
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.19
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  youtube_player_flutter: ^9.1.1

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
